### ISSUE TITLE
Create 3.3.1-stable Tag/Release with extracted_headers.zip

### ISSUE THREAD

**Issue by gumaciel** [godotengine/godot-ios-plugins#12]
Like this one: https://github.com/godotengine/godot-ios-plugins/releases/tag/3.3-stable

The reason why this is important: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/runs/2643467232?check_suite_focus=true

I'm trying to compile a Job of my plugin and the Job downloads the extracted-headers.zip to maximize the speed of building the plugin for iOS

**Comment by Calinou** [comment]
cc @naithar

**Comment by naithar** [comment]
This should do it: https://github.com/godotengine/godot-ios-plugins/releases/tag/3.3.1-stable. 
Sorry missed the stable release :)

**Comment by gumaciel** [comment]
It works, thank you so much!
