### ISSUE TITLE
GameCenter Plugin award_achievement not displaying banner

### ISSUE THREAD

**Issue by Tekuzo** [godotengine/godot-ios-plugins#13]
I am using the GameCenter plugin in my game and following the [documentation](https://docs.godotengine.org/en/stable/tutorials/platform/ios/plugins_for_ios.html#game-center) I call award_achievement() from within a function that I have connected to a signal that various nodes can emit when their criteria is true.

```
func unlock_achievement(name):
     Singleton.award_achievement({"name": name, "progress": 100.0, "show_completion_banner": true});
```

When the signal is emitted the achievement is awarded because I can go and check my awarded achievements with the show_game_center( { "view": "achievements" } )) function. So the function mostly works, its just not displaying the banner.

**Comment by Calinou** [comment]
cc @naithar

**Comment by naithar** [comment]
> So the function mostly works, its just not displaying the banner.

Was it working before?

I guess something goes wrong with this line https://github.com/godotengine/godot-ios-plugins/blob/master/plugins/gamecenter/game_center.mm#L166.

**Comment by Tekuzo** [comment]
No, it never worked to my knowledge. I just got achievements unlocking yesterday and did a bit of testing then decided to submit my bug report.

**Comment by Tekuzo** [comment]
I take it back, it just randomly started working. Maybe I had a typo in my code.

Sorry for the confusion.
