### ISSUE TITLE
APN for 3.3

### ISSUE THREAD

**Issue by Zarasan** [godotengine/godot-ios-plugins#15]
Why is APN not built for version 3.3?

**Comment by naithar** [comment]
You can use `master` branch plugins with Godot 3.3.
`3.3` branch is made to keep same API that was present in Godot 3.2 iOS modules.

**Comment by Zarasan** [comment]
<img width="853" alt="Screenshot 2021-06-08 at 14 52 35 1" src="https://user-images.githubusercontent.com/43384612/121188278-40402900-c869-11eb-9db8-da741cd185c1.png">
I used master branch with Godot 3.3.2 stable and get these errors when exporting

**Comment by naithar** [comment]
Godot does not provide `armv7` binaries for iOS.
Which mode were you using when exporting the project - `debug` or `release`?

**Comment by naithar** [comment]
Just tested with Godot 3.3.2 and 3.3.2 APN plugin. 
Everything builds and works fine - both `release` and `debug` export mode. 
You should provide minimal reproduction project if problem is not related to the incorrect plugin version.

**Comment by naithar** [comment]
Manually switching to the incorrect plugin binaries (`debug` plugin for `release` iOS template and `release` plugin for `debug` iOS template) resulted in the error you are having. 
I suggest double checking plugin version you are using and reexporting your project. You should probably use a different directory and run `Product->Clean Build Folder` as `.xcframework` caches it's build files, so you might be getting incorrect binaries from that.

**Comment by Zarasan** [comment]
Switching to build to phone and not simulated and changed build sdk to ios 13.5 everything worked and was able to send a notification to my app.
