### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by phil-hudson** [godotengine/godot-ios-plugins#49]
As per title.

**Comment by Calinou** [comment]
We still intend to maintain it, but @naithar is no longer available to work on it. As a result, we'll need other contributors to continue this work :slightly_smiling_face: 

Note that most Godot contributors are not knowledgeable with the iOS platform. Many of them don't have access to any iOS device, or even a macOS device to run the simulator on.

Closing in favor of https://github.com/godotengine/godot-ios-plugins/issues/47.
