### ISSUE TITLE
Possibility to add other types of keys on [plist], such as Array

### ISSUE THREAD

**Issue by gustavottc** [godotengine/godot-ios-plugins#5]
For some Plugins this should be very good, one example is AdMob: https://developers.google.com/admob/ios/quick-start#update_your_infoplist

Needs to be placed three different type of keys: string, dict and array

- Thought-out solution:

Instead of [plist] it goes like this:

```
PlistKey = "Some Info.plist key you might need"
```

it could be like this:

```
<key>
     PlistKey
</key>
<string>
     Some Info.plist key you might need
</string>
```

So when exporting the project to iOS, the Engine will copy and paste what is in [plist] inside the Xcode project's .plist

**Comment by naithar** [comment]
I guess something like `Key:type = "<Value>"` could be done for this section, like 
```
PlistKeyOld="value"
PlistKey1:string = "value"
PlistKey2:raw = "<key>PlistKey2</key><string>Some Info.plist key you might need</string>"
```
Maybe even something like `PlistKey3:export="Value that can be specified in export dialog"` so users could specify specific values directly in editor without modifying Xcode project.

**Comment by gustavottc** [comment]
Maybe i can help you do to that, the branch that i work for `ios-plugins` is this? https://github.com/naithar/godot/tree/fix/ios-plugin

Can you tell to me where is the part when read the `.gdip` file and write the `.plist` of project?

**Comment by naithar** [comment]
> Maybe i can help you do to that, the branch that i work for `ios-plugins` is this? https://github.com/naithar/godot/tree/fix/ios-plugin
> 
> Can you tell to me where is the part when read the `.gdip` file and write the `.plist` of project?

You should branch out from current `3.x` and `master`, not my fork. 
[godot_plugin_config.h](https://github.com/naithar/godot/blob/fix/ios-plugin/platform/iphone/plugin/godot_plugin_config.h) and [export.cpp](https://github.com/naithar/godot/blob/fix/ios-plugin/platform/iphone/export/export.cpp) are files you are looking for.

**Comment by gustavottc** [comment]
Thanks, I will close the issue since the implementation has to be done in another repository, I will try to develop but I think I will not be able to because of the export templates, I find it very difficult to create these templates on mac.
