### ISSUE TITLE
error when build ARKit for 4.1.1

### ISSUE THREAD

**Issue by waci11** [godotengine/godot-ios-plugins#51]
I fixed few errors that I can understand，like change Transform to Transform3D .
but still have 7 errors I have no idea how to fix .

the errors:

In file included from plugins/arkit/arkit_module.cpp:33:
plugins/arkit/arkit_interface.h:108:15: error: 'notification' marked 'override' but does not override any member functions [2]
        virtual void notification(int p_what) GODOT_ARKIT_OVERRIDE;
                      ^
plugins/arkit/arkit_interface.h:117:16: error: 'get_render_targetsize' marked 'override' but does not override any member functions [2]
        virtual Size2 get_render_targetsize() GODOT_ARKIT_OVERRIDE;
                       ^
plugins/arkit/arkit_interface.h:118:15: error: 'is_stereo' marked 'override' but does not override any member functions [2]
        virtual bool is_stereo() GODOT_ARKIT_OVERRIDE;
                      ^
plugins/arkit/arkit_interface.h:119:22: error: 'get_transform_for_eye' marked 'override' but does not override any member functions [2]
        virtual Transform3D get_transform_for_eye(GodotBaseARInterface::EnvironmentBlendMode evn,  const Transform3D &p_cam_transform) GODOT_ARKIT_OVERRIDE;
                             ^
plugins/arkit/arkit_interface.h:120:21: error: 'get_projection_for_eye' marked 'override' but does not override any member functions [2]
        virtual Projection get_projection_for_eye(GodotBaseARInterface::EnvironmentBlendMode evn, real_t p_aspect, real_t p_z_near, real_t p_z_far) GODOT_ARKIT_OVERRIDE;
                            ^
plugins/arkit/arkit_interface.h:121:15: error: 'commit_for_eye' marked 'override' but does not override any member functions [2]
        virtual void commit_for_eye(GodotBaseARInterface::EnvironmentBlendMode evn, RID p_render_target, const Rect2 &p_screen_rect) GODOT_ARKIT_OVERRIDE;
                      ^
plugins/arkit/arkit_module.cpp:40:18:{40:2-40:17}: error: no member named 'instance' in 'Ref<ARKitInterface>' [2]
        arkit_interface.instance();
         ~~~~~~~~~~~~~~~ ^

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-ios-plugins/issues/47. Please keep discussion about updating these plugins focused to a single issue.
