### ISSUE TITLE
Any update on support for Godot 4.x?

### ISSUE THREAD

**Issue by amanatron** [godotengine/godot-ios-plugins#52]
I've been following up with the recent thread on the same but the processes mentioned for compiling the plug-in/Godot are way above my pay grade. I was wondering if anyone has any update on what the status is on the future of these plugins?

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-ios-plugins/issues/47. Please keep discussion about updating these plugins focused to a single issue.
