### ISSUE TITLE
Add more than one binary at the same time

### ISSUE THREAD

**Issue by gustavottc** [godotengine/godot-ios-plugins#6]
I am currently developing a [Plugin with AdMob](https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/tree/iOS-Plugin) in which I need in addition to exporting the plugin I created, I also need to export these ```.xcframework``` to be able to work

![Captura de Tela 2021-04-08 às 00 07 29](https://user-images.githubusercontent.com/20030153/113962612-6b24e700-97fe-11eb-8ccd-365fb4908b66.png)

This could work:

```
[config]
name="MyPlugin"
binary="MyPlugin.a"
```
Change to array: 
```
[config]
name="MyPlugin"
binary=["MyPlugin.a", "OtherBinary.a"]
```

**Comment by gustavottc** [comment]
I created another "plugin" only with the ```.xcframework``` and works.

![Captura de Tela 2021-04-08 às 00 12 24](https://user-images.githubusercontent.com/20030153/113962993-2b123400-97ff-11eb-8e8a-34a4b0526133.png)


But i won't do that because when export the Project will need to enable all plugins:
![Captura de Tela 2021-04-08 às 00 13 56](https://user-images.githubusercontent.com/20030153/113963071-509f3d80-97ff-11eb-8af3-906da93de436.png)

And i want only one plugin that have more than one binary (which are dependencies), not a lot of Plugins

Also works when add the ```.xcframework``` manually, but i want to do this automatically.

**Comment by naithar** [comment]
`dependencies` section and  `linked`/`embedded` field should actually help with copying third party dependency frameworks to the Xcode projects.

**Comment by gustavottc** [comment]
Everything works, but this framework "PromisesObjC.xcframework" always gives error, do you know why?

![Captura de Tela 2021-04-08 às 10 07 16](https://user-images.githubusercontent.com/20030153/114031914-33e02580-9852-11eb-97b9-fd92bee19a58.png)


![Captura de Tela 2021-04-08 às 10 08 03](https://user-images.githubusercontent.com/20030153/114032023-4f4b3080-9852-11eb-938e-8d78f59fd60d.png)

**Comment by gustavottc** [comment]
![Captura de Tela 2021-04-08 às 10 10 26](https://user-images.githubusercontent.com/20030153/114032391-a5b86f00-9852-11eb-80e3-d22349a6d170.png)

**Comment by gustavottc** [comment]
You can check the SDK that i am using here: https://dl.google.com/googleadmobadssdk/googlemobileadssdkios.zip

**Comment by naithar** [comment]
https://github.com/naithar/godot/blob/576f0f14b224a0086675dd5da5a5c1a66856e111/platform/iphone/export/export.cpp#L1337-L1347
This lines are responsible for dependencies handling. 
I haven't tested them with `xcframework`s, since at that time `xcframework` wasn't even supported, so there might be some problem with it. 
But I'm also not sure about the path that gets copied - `PromiseObjC.framework/Headers/Headers` doesn't seem correct to me. Seems like the problem might be related to it.

**Comment by naithar** [comment]
@gustavottc Yeah the file (?) at `PromiseObjC.framework/Headers/Headers` path seems to be corrupted. Can you delete it and check if it'll work for you?

**Comment by gustavottc** [comment]
@naithar Ty so much, when i delete this file worked!

As i see this was a simlimk i will contact Google to try to fix this on next version.
