### ISSUE TITLE
Error/warning when exporting: Failed to get modified time for, when bin is '.xcframework'

### ISSUE THREAD

**Issue by gustavottc** [godotengine/godot-ios-plugins#7]
The project on Xcode works normally, but on Godot it gives me this warning or error:
![Captura de Tela 2021-04-12 às 21 52 16](https://user-images.githubusercontent.com/20030153/114481001-0bea1c80-9bda-11eb-831a-29ca435061fe.png)

SDK AdMob: https://dl.google.com/googleadmobadssdk/googlemobileadssdkios.zip
Plugin:[admob_plugin.zip](https://github.com/godotengine/godot-ios-plugins/files/6300591/admob_plugin.zip)

**Comment by naithar** [comment]
You should probably report it in Godot repository, since this repo is for plugins only, not plugin system itself.

**Comment by gustavottc** [comment]
Sorry about that and thank you for solving fast!
